### ISSUE TITLE
Jabber/XMPP Notification Error

### ISSUE THREAD

**Issue by jpaechnatz** [kanboard/kanboard#2699]
### Expected behaviour

Due Notification via Jabber/XMPP Plugin
### Actual behaviour

Notification Mail is send, Jabber notification fails. No Entry in debug.log about jabber plugin.

obbala@phoenix kanboard]$ ./kanboard cronjob
PHP Notice:  Undefined index: task in /var/www/virtual/obbala/html/kanboard/plugins/Jabber/Notification/Jabber.php on line 35
PHP Catchable fatal error:  Argument 1 passed to Kanboard\Plugin\Jabber\Notification\Jabber::getMessage() must be of the type array, null given, called in /var/www/virtual/obbala/html/kanboard/plugins/Jabber/Notification/Jabber.php on line 39 and defined in /var/www/virtual/obbala/html/kanboard/plugins/Jabber/Notification/Jabber.php on line 111
### Steps to reproduce

Manually or cronjob causes this error. 
### Configuration

Jabber:
tcp://geknupp.de:65423
Domain: geknupp.de
User & Password

Version: master
PHP Version: 5.6.21
PHP SAPI: cgi-fcgi
OS Version: Linux 2.6.32-504.8.1.el6.x86_64
Datenbanktreiber: sqlite
Datenbank Version: 3.8.10.2
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.34 Safari/537.36

**Comment by fguillot** [comment]
Which version of master are you using and which version of the Jabber plugin?

**Comment by jpaechnatz** [comment]
git log -p -1
commit 2f64bc2e8d6dd17eafd8238db66c682199281e45
Merge: 8854933 76b4f63
Author: Frédéric Guillot <fred@kanboard.net>
Date:   Tue Sep 27 17:43:50 2016 -0400

    Merge pull request #2703
    
    Avoid "Controller not found"

git show-branch
[master] Merge pull request #2703


Jabber 1.0.5

**Comment by felicson** [comment]
hi!
Sorry my English.
I have a same problem on my instance!
kanban version 1.0.33
jabber plugin version 1.0.5

**Comment by andresth** [comment]
Hi @fguillot,

i had the same problem, so i decided to look into it.

The error is in the file `Notification/Jabber.php` of the Jabber plugin.
There you try access the `task` field of the `$event_data` array, which does not exist.
I think it should be `$event_data['tasks'][0][something]`.

I attached a patch which works fine for me.

I hope that helps you.

Greetings Thomas

[Jabber.php.patch.txt](https://github.com/kanboard/kanboard/files/546419/Jabber.php.patch.txt)

**Comment by andresth** [comment]
I realized that I fixed the overdue notifications but broke all the other notifications.

You can find my updated code here:  
https://github.com/andresth/plugin-jabber

Now all the notifications work, I also added more informations to the message text as requested in issue #2224.

**Comment by stefanjay** [comment]
Hey Thomas,

thanks for the patch. Problem isn't solved for me/us. Kanboard version is 1.0.37; jabber v1.0.5 (orig. 1.0.6). I tried both patches. Jabber/ XMPP works correctly and was correctly configured in kanboard.

Problem: - no notifications to jabber room/user when creating/update/add a project/ user to

Any ideas?

Greetings, Stefan.

**Comment by andresth** [comment]
Hi Stefan,

as far as I know there are no events for projects or users.
This actions are also not shown in the activity stream or sent out by email.

The events I found in the source code are for
* Tasks
* Subtasks
* Comments
* Files

These notifications should work if you cloned the notifiction_fix branch from my repository.

Maybe you should add a feature request for this.

Greetings Thomas

**Comment by stefanjay** [comment]
Thank you for your reply. 

I rolled back to php56 (from 7.0.14) with all the needed dependencies for kanboard. It does not work either. 

Greetings, Stefan

**Comment by fguillot** [comment]
You can now download the version 1.0.7 of the plugin to avoid this error. Thank you.
