### ISSUE TITLE
Role lost on LDAP login after upgrade to 1.2.16

### ISSUE THREAD

**Issue by rafacamargo123** [kanboard/kanboard#4640]
### Actual behaviour

After loggin in with LDAP the user loses its current setted roles (admin, manager) and is setted as USER.

### Expected behaviour

The previous behaviour on kanboard allowed users to have roles setted manually.

### Steps to reproduce

login with LDAP with an user that doesn't matches LDAP_GROUP_ADMIN_DN or LDAP_GROUP_MANAGER_DN

login with an admin user and set the previous user as ADMIN or MANAGER

login again with the previous user. His role is removed

### Configuration

- Versão da aplicação: v1.2.16
- Versão do PHP: 7.3.23
- PHP SAPI: fpm-fcgi
- Cliente HTTP: cURL
- Versão do sistema operacional: Linux 3.10.0-1062.4.1.el7.x86_64
- Driver do banco de dados: mysql
- Versão do banco de dados: 5.7.9-log
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36

I believe this behaviour was introduced by e3e9cabd8bfba57eedd4e820bcd6c0ace34eb80c - #4384

**Comment by Floyer007** [comment]
Same behaviour for me as well.

Only difference: I'm using sqlite as database-driver.

**Comment by inful** [comment]
Same problem

**Comment by simonjamain** [comment]
same

**Comment by ChristianSwift** [comment]
楼上几位大哥都不读文档的吗？[点我](https://docs.kanboard.org/en/1.2.16/admin_guide/ldap_authentication.html#synchronization)

**Comment by Floyer007** [comment]
How should this solve the problem?
Everything in the list will _not_ be synchronized.

I've only "username" in my list.

**Comment by ChristianSwift** [comment]
> How should this solve the problem?
> Everything in the list will _not_ be synchronized.
> 
> I've only "username" in my list.

只要你用了LDAP登陆方式而且不指定用户组的DN那么每次登陆的时候都会自动同步一次角色到数据库里，除非你在同步选项中把角色同步功能排除出去，文档里就有一模一样的例子。
![image](https://user-images.githubusercontent.com/20925565/100818736-b52f4200-3485-11eb-9938-df6d83d9d66c.png)
求求你们读一下文档吧！！！！

**Comment by ChristianSwift** [comment]
> How should this solve the problem?
> Everything in the list will _not_ be synchronized.
> 
> I've only "username" in my list.

都用上LDAP了，干嘛还要手动指定用户成超管啊，直接在LDAP里指定一个用户组做超管不香吗？

**Comment by fguillot** [comment]
@rafacamargo123 Does PR #4674 fixes the issue?

**Comment by fguillot** [comment]
v1.2.17 has been released. The PR above should fix the issue.

**Comment by rafacamargo123** [comment]
I'm sorry for the delay, I was away from work and I could test it just now.
The version 1.2.17 has fixed it.

**Comment by Floyer007** [comment]
Did you change anything else?

It still not seem to work for me.
I'm using v1.2.18.

My LDAP admin-user still falls back to "User", even if I change its role to "Administrator" manually via a local administrator.
(If I enable LDAP_USER_DEFAULT_ROLE_MANAGER it switches to "Manager".)

The user has the following LDAP-groups:
- t_admin (mapped as LDAP_GROUP_ADMIN_DN)
- t_active (should be its own group)

The user is neither grouped either in t_active nor get his administrator rule.
